### ISSUE TITLE
[L1] CNF with MSSQL

### ISSUE THREAD

**Issue by lasanthaS** [siddhi-io/siddhi-io-cdc#60]
**Description:**
Following error occurs when connecting to Microsoft SQL server with siddhi-io-cdc-2.0.6 connector. This works fine with siddhi-io-cdc-2.0.5 connector.

```
io.siddhi.core.exception.ConnectionUnavailableException: Connection to the database lost.
	at io.siddhi.extension.io.cdc.source.CDCSource.lambda$connect$1(CDCSource.java:503)
	at io.debezium.embedded.EmbeddedEngine.run(EmbeddedEngine.java:899)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.NoClassDefFoundError: com/microsoft/sqlserver/jdbc/SQLServerDriver
	at io.debezium.connector.sqlserver.SqlServerConnection.<clinit>(SqlServerConnection.java:60)
	at io.debezium.connector.sqlserver.SqlServerConnectorTask.start(SqlServerConnectorTask.java:87)
	at io.debezium.connector.common.BaseSourceTask.start(BaseSourceTask.java:49)
	at io.debezium.embedded.EmbeddedEngine.run(EmbeddedEngine.java:793)
	... 3 more
Caused by: java.lang.ClassNotFoundException: com.microsoft.sqlserver.jdbc.SQLServerDriver cannot be found by siddhi-io-cdc_2.0.6
	at org.eclipse.osgi.internal.loader.BundleLoader.findClassInternal(BundleLoader.java:448)
	at org.eclipse.osgi.internal.loader.BundleLoader.findClass(BundleLoader.java:361)
	at org.eclipse.osgi.internal.loader.BundleLoader.findClass(BundleLoader.java:353)
	at org.eclipse.osgi.internal.loader.ModuleClassLoader.loadClass(ModuleClassLoader.java:161)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 7 more
```

**Affected Product Version:**
2.0.6

**OS, DB, other environment details and versions:**    
JDBC driver: sqljdbc42.jar
